#!/bin/bash
#SBATCH -J SPARC_testsuite
#SBATCH -A hive-amedford6                    # Account name
#SBATCH -p hive                             # Partition
#SBATCH -N 2 --ntasks-per-node=24
#SBATCH --mem-per-cpu=7G
#SBATCH -t2:00:00
cd $SLURM_SUBMIT_DIR

module reset
module load mkl
echo $PWD 



